export const APPLICATION_STATUS = {
  PENDING: 'En attente',
  REVIEWING: 'En cours d\'examen',
  INTERVIEW: 'Entretien planifié',
  ACCEPTED: 'Acceptée',
  REJECTED: 'Refusée',
};

export const STATUS_COLORS = {
  'En attente': {
    bg: 'bg-yellow-100',
    text: 'text-yellow-800',
    dot: 'bg-yellow-500',
  },
  'En cours d\'examen': {
    bg: 'bg-blue-100',
    text: 'text-blue-800',
    dot: 'bg-blue-500',
  },
  'Entretien planifié': {
    bg: 'bg-purple-100',
    text: 'text-purple-800',
    dot: 'bg-purple-500',
  },
  'Acceptée': {
    bg: 'bg-green-100',
    text: 'text-green-800',
    dot: 'bg-green-500',
  },
  'Refusée': {
    bg: 'bg-red-100',
    text: 'text-red-800',
    dot: 'bg-red-500',
  },
};

export const STAGE_TYPES = [
  'Stage PFE',
  'Stage d\'été',
  'Stage d\'observation',
  'Stage pré-embauche',
  'Alternance',
];

export const DEPARTMENTS = [
  'Développement Web',
  'Développement Mobile',
  'Data Science & IA',
  'DevOps & Cloud',
  'UI/UX Design',
  'Gestion de Projet',
  'Cybersécurité',
  'Ressources Humaines',
];

export const EDUCATION_LEVELS = [
  'Bac +2 (BTS/DUT)',
  'Bac +3 (Licence)',
  'Bac +4 (Master 1)',
  'Bac +5 (Master 2 / Ingénieur)',
  'Doctorat',
];

export const HR_CREDENTIALS = {
  email: 'rh@grouperif.com',
  password: 'rif2024',
};

export const MOCK_CANDIDATES = [
  {
    id: '1',
    firstName: 'Ahmed',
    lastName: 'Ben Ali',
    email: 'ahmed.benali@email.com',
    phone: '+216 55 123 456',
    dateOfBirth: '1999-05-15',
    educationLevel: 'Bac +5 (Master 2 / Ingénieur)',
    university: 'ESPRIT',
    stageType: 'Stage PFE',
    department: 'Développement Web',
    startDate: '2024-02-01',
    endDate: '2024-07-31',
    motivation: 'Passionné par le développement web et les technologies modernes, je souhaite mettre en pratique mes compétences acquises durant ma formation.',
    skills: 'React, Node.js, Firebase, Tailwind CSS',
    cvUrl: '#',
    status: 'En attente',
    submittedAt: '2024-01-15T10:30:00',
  },
  {
    id: '2',
    firstName: 'Sara',
    lastName: 'Trabelsi',
    email: 'sara.trabelsi@email.com',
    phone: '+216 22 987 654',
    dateOfBirth: '2000-08-22',
    educationLevel: 'Bac +3 (Licence)',
    university: 'FST Tunis',
    stageType: 'Stage d\'été',
    department: 'Data Science & IA',
    startDate: '2024-06-01',
    endDate: '2024-08-31',
    motivation: 'Je souhaite approfondir mes connaissances en intelligence artificielle et machine learning au sein d\'une entreprise innovante.',
    skills: 'Python, TensorFlow, SQL, Power BI',
    cvUrl: '#',
    status: 'En cours d\'examen',
    submittedAt: '2024-01-20T14:15:00',
  },
  {
    id: '3',
    firstName: 'Mohamed',
    lastName: 'Khelifi',
    email: 'mohamed.khelifi@email.com',
    phone: '+216 98 456 789',
    dateOfBirth: '1998-12-03',
    educationLevel: 'Bac +5 (Master 2 / Ingénieur)',
    university: 'INSAT',
    stageType: 'Stage PFE',
    department: 'DevOps & Cloud',
    startDate: '2024-03-01',
    endDate: '2024-08-31',
    motivation: 'Motivé par les pratiques DevOps et l\'automatisation, je cherche à contribuer activement à des projets cloud innovants.',
    skills: 'Docker, Kubernetes, AWS, CI/CD, Linux',
    cvUrl: '#',
    status: 'Acceptée',
    submittedAt: '2024-01-10T09:00:00',
  },
  {
    id: '4',
    firstName: 'Yasmine',
    lastName: 'Gharbi',
    email: 'yasmine.gharbi@email.com',
    phone: '+216 54 321 098',
    dateOfBirth: '2001-03-18',
    educationLevel: 'Bac +4 (Master 1)',
    university: 'Université de Carthage',
    stageType: 'Stage d\'observation',
    department: 'UI/UX Design',
    startDate: '2024-04-01',
    endDate: '2024-05-31',
    motivation: 'Créative et passionnée par le design d\'interfaces, je souhaite observer et apprendre les meilleures pratiques UX en entreprise.',
    skills: 'Figma, Adobe XD, Illustrator, Photoshop',
    cvUrl: '#',
    status: 'Entretien planifié',
    submittedAt: '2024-01-25T16:45:00',
  },
  {
    id: '5',
    firstName: 'Karim',
    lastName: 'Mansouri',
    email: 'karim.mansouri@email.com',
    phone: '+216 27 654 321',
    dateOfBirth: '1999-11-07',
    educationLevel: 'Bac +5 (Master 2 / Ingénieur)',
    university: 'ENIS Sfax',
    stageType: 'Stage pré-embauche',
    department: 'Développement Mobile',
    startDate: '2024-01-15',
    endDate: '2024-06-15',
    motivation: 'Fort d\'une expérience en développement mobile cross-platform, je cherche une opportunité de stage pré-embauche pour intégrer une équipe dynamique.',
    skills: 'Flutter, Dart, React Native, Firebase',
    cvUrl: '#',
    status: 'Refusée',
    submittedAt: '2024-01-05T11:20:00',
  },
  {
    id: '6',
    firstName: 'Amira',
    lastName: 'Bouazizi',
    email: 'amira.bouazizi@email.com',
    phone: '+216 93 111 222',
    dateOfBirth: '2000-07-25',
    educationLevel: 'Bac +3 (Licence)',
    university: 'ISI Tunis',
    stageType: 'Alternance',
    department: 'Cybersécurité',
    startDate: '2024-09-01',
    endDate: '2025-06-30',
    motivation: 'La cybersécurité est ma passion. Je souhaite contribuer à la protection des systèmes d\'information tout en développant mes compétences.',
    skills: 'Kali Linux, Wireshark, Python, Pentesting',
    cvUrl: '#',
    status: 'En attente',
    submittedAt: '2024-01-28T08:30:00',
  },
];

export const MOCK_INTERVIEWS = [
  {
    id: '1',
    candidateName: 'Sofia Rodrigues',
    company: 'BNP Paribas Corporate',
    date: '2025-07-07',
    time: '10:00',
    type: 'Visio',
    status: 'Confirmé',
    color: '#EF4444',
  },
  {
    id: '2',
    candidateName: 'Théo Marchetti',
    company: 'Capgemini Engineering',
    date: '2025-07-08',
    time: '14:30',
    type: 'Présentiel',
    status: 'En attente',
    color: '#3B82F6',
  },
  {
    id: '3',
    candidateName: 'Amira Benali',
    company: 'Thales Group',
    date: '2025-07-09',
    time: '11:00',
    type: 'Visio',
    status: 'Confirmé',
    color: '#A855F7',
  },
  {
    id: '4',
    candidateName: 'Nour El Amrani',
    company: 'Orange Cyberdefense',
    date: '2025-07-10',
    time: '15:00',
    type: 'Visio',
    status: 'En attente',
    color: '#F59E0B',
  },
  {
    id: '5',
    candidateName: 'Ahmed Ben Ali',
    company: 'Sopra Steria',
    date: '2025-07-11',
    time: '09:30',
    type: 'Présentiel',
    status: 'Confirmé',
    color: '#10B981',
  },
];